services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./todo-app/backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./todo-app/frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-sbse.onrender.com